version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore DronZone-API/DronZone-API.csproj
      - dotnet restore UnitTests/UnitTests.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output DronZone-API/DronZone-API.csproj
      - dotnet publish -c release -o ./test_output UnitTests/UnitTests.csproj
      - dotnet vstest UnitTests/test_output/UnitTests.dll
  # post_build:
  #   commands:
artifacts:
  files:
    - template.yml
    - DronZone-API/build_output/**/*
    # - UnitTests/test_output/**/*
    - scripts/**/*
    - appspec.yml
    - template-configuration.json
